export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FILTER_PRODUCTS_FROM_PRICE = "FILTER_PRODUCTS_FROM_PRICE";
export const FILTER_PRODUCTS_TO_PRICE = "FILTER_PRODUCTS_TO_PRICE";
export const FILTER_PRODUCTS_BY_KEYWORD = "FILTER_PRODUCTS_BY_KEYWORD";
export const RESET_FILTERS = "RESET_FILTERS";
